module.exports.message = ({
    registerSuccess: "Registered Successfully",
    login: "Login Succesfully",
    loginFailed: "User Name or Password is Invalid",
    emailExist: "Email Already Exists",
    wrongPassword: "User Name or Password is Invalid",
    alreadyLogin: "User Already Logged In",
    invalidCredential: "Invalid credentials",
    inValid: "Invalid Request",
    logoutSucess: "User logged out Successfully",
    invalidUserId: "Invalid Request",
    invalidId: "Invalid ID",
    invalidScheduleId: "Invalid Schedule Id",
    verifiedEmail: "Email Verified",
    otpVerified: "OTP Verified",
    otpResend: "OTP sent successfully",
    userNotFound: "Bad Request",
    sendMail: "Mail sent successfully",
    updatedSucess: "Updated successfully",
    addedUserDetailsSucess: "User Details Added Successfully",
    userDetailsUnsucess: "User Under Verification",
    statusUpdatedSucess: "Status Updated Successfully",
    dataFoundSucess: "Data Found SuccessFully",
    dataNotFound: "Data Not Found",
    wrongCurrentPassword: "Current Password Is wrong",
    costheadingExist: "Cost Heading Already Exists",
    costheadingAddedSucess: "Cost Heading Added Successfully",
    addedCountryCitySucess: "County City List Added Sucessfully",
    countryExist: "Country Already Exists",
    addedGroupSucess: "Group Added Successfully",
    chatSentSucess: "Chat sent Successfully",
    updateGroupSucess: "Group Updated Successfully",
    removeUserGroupSucess: "User Removed From Group Successfully",
    notFoundTicket: "Ticket Not Found",
    passwordCreated: "Password Created Successfully",
    deletedSucess: "Deleted Successfully",
    updatedPayment: "Updated Payment Details",
    forgotOtpmismatched : "Request Failed, Please try again",
    invalidCustomerId:"Customer Id is required",
    ticketInserted:"Ticket Inserted Successfully"
})


