module.exports.message = ({
    registerSuccess: "Registered Successfully",
    login: "Login Succesfully",
    loginFailed: "User Name or Password is Invalid",
    emailExist: "Email Already Exists",
    panExist: "PAN Already Exists",
    gstExist: "GST Already Exists",
    mtoExist: "MTO Already Exists",
    wrongPassword: "User Name or Password is Invalid",
    alreadyLogin: "User Already Logged In",
    invalidCredential: "Invalid credentials",
    inValid: "Invalid Request",
    logoutSucess: "User logged out Successfully",
    invalidUserId: "Invalid Request",
    invalidId: "Invalid ID",
    invalidScheduleId: "Invalid Schedule Id",
    verifiedEmail: "Email Verified",
    otpVerified: "OTP Verified",
    otpResend: "OTP sent successfully",
    userNotFound: "Bad Request",
    sendMail: "Mail sent successfully",
    updatedSucess: "Updated successfully",
    addedUserDetailsSucess: "User Details Added Successfully",
    userDetailsUnsucess: "User Under Verification",
    statusUpdatedSucess: "Status Updated Successfully",
    dataFoundSucess: "Data Found SuccessFully",
    dataNotFound: "Data Not Found",
    wrongCurrentPassword: "Current Password Is wrong",
    costheadingExist: "Cost Heading Already Exists",
    costheadingAddedSucess: "Cost Heading Added Successfully",
    addedCountryCitySucess: "County City List Added Sucessfully",
    countryExist: "Country Already Exists",
    addedCountrySucess: "Country Added Successfully",
    notFoundCountry: "Country Not Found",
    laneExist: "Lane Already Exists",
    addedLaneSucess: "Lane Added Successfully",
    notFoundLane: "Lane Not Found",
    notFoundCostHeading: "Cost Heading Not Found",
    addedHolidaySucess: "Holiday Added Successfully",
    holidayExist: "Holiday Already Exists ",
    notFoundHoliday: "Holiday Not Found",
    addedScheduleSucess: "Schedule Added Successfully",
    notFoundSchedule: "Schedule Not Found",
    cfsExist: "CFS Already Exists",
    addedCfsSucess: "CFS Added Successfully",
    notFoundCfs: "CFS Not Found",
    addedRateSucess: "Rate Added Successfully",
    scheduleIdExist: "scheduleId Already Exist",
    notFoundRate: "Rate Not Found",
    updateOF: "Updated Successfully",
    updateDF: "Updated Successfully",
    updateNP: "Updated Successfully",
    updateCheckoutDetails: "Updated Checkout Details Successfully",
    updateDOCS: "Updated DOCS Successfully",
    updateBooking: "Updated Booking Successfully",
    addedSucess: "Added Successfully",
    addedSucessBS: "Booking Search Added Successfully",
    fileDownloaded: "File Downloaded Successfully",
    bookingNotFound: "Booking Not Found",
    subUserAdded: "User Added Successfully",
    maxUsers: "Maximum Users Added",
    passwordCreated: "Password Created Successfully",
    deletedSucess: "Deleted Successfully",
    updatedPayment: "Updated Payment Details",
    invalidBookingId: "Invalid Booking ID",
    milestoneSucess: "Milestone Added Successfully",
    containerFilled: "Container Volume Exceeded",
    loginExceeded: "You\'ve reached maximum tries & Check Your Mail to Reset Password",
    hsnAddSucess: "Hsn Added SuccessFully",
    forgotOtpmismatched : "Request Failed, Please try again",
    invalidCustomerId:"Customer Id is required"
    
})


